baseURL = ''
title = 'FarmFrontiers'
languageCode = 'en-us'
DefaultContentLanguage = 'en'
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
canonifyURLs = true
enableInlineShortcodes = true

[pagination]
  pagerSize = 6

[darkmode_js]
  assets = ['assets/js/darkmode.js']

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = false
        title = true
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[params]
  author = 'Pushpz'
  logo = "static/favicon/android-chrome-192x192.png"
  authorimage = "../assets/images/global/author.webp"
  og_image = 'images/pages/farm (5).jpeg'
  moto = "Exploring the New Age of Agriculture"
  description = "Revolutionizing Agriculture with Modern Technology. Empowering Farmers with Smart Solutions & Knowledge"
  disable_theme_toggle = false
  disable_stay_uptodate = false
  customCSS = ["css/custom.css"]

[taxonomies]
  category = 'Categories'
  tag = 'Tags'

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = '0.114.0'

[params.p1]
  heading = "Transforming Farming with Innovation"
  image = "/images/pages/farm (8).jpg"

[[params.p1.content]]
  text = "Agriculture is transforming with smart farming, AI, and IoT, enabling real-time crop monitoring and efficient resource management. Drones and automated irrigation boost productivity while cutting costs."

[[params.p1.content]]
  text = "Precision agriculture optimizes farming with GPS, sensors, and analytics. Hydroponics and vertical farming offer soil-free solutions, ensuring sustainable food production in limited spaces."

[[params.p1.content]]
  text = "Biotechnology enhances crops with pest resistance and climate adaptability. AI-driven recommendations and robotic harvesting make farming smarter and more efficient for the future."

[params.p2]
  heading = "Life at Punjab Agricultural University (PAU)"
  image = "/images/pages/farm (1).jpg"

[[params.p2.content]]
  text = "PAU is more than just a college; it’s a place where passion for agriculture meets innovation. From research labs to lush green fields, every corner of the campus inspires growth and learning. The hands-on experience and supportive mentors make the journey truly enriching."

[[params.p2.content]]
  text = "Beyond academics, PAU is a vibrant community filled with cultural events, student clubs, and friendships that last a lifetime. Whether it’s late-night study sessions or celebrations after a successful harvest, every moment here becomes a cherished memory"

[[params.p2.content]]
  text = "Walking through the campus, I feel a deep connection to agriculture and the people shaping its future. PAU has not only given me knowledge but also a purpose—to contribute to the farming community with innovation and heart."

[params.p3]
  heading = "Tech Journey & Future in AgriTech"

[[params.p3.content]]
  text = "Exploring the power of Python, HTML, and JavaScript, I’ve been working on diverse projects while gearing up for AgriTech innovations"

[[params.p3.links]]
  text = "Discover Innovations and What's Being Built"
  url = "/posts/"

[[params.p3.logos]]
  identifier = "a"
  image = "images/LOGO/HTML.png"
  alt = "HTML Logo"

[[params.p3.logos]]
  identifier = "b"
  image = "images/LOGO/CSS.png"
  alt = "CSS Logo"

[[params.p3.logos]]
  identifier = "c"
  image = "images/LOGO/JS.png"
  alt = "JavaScript Logo"

[[params.p3.logos]]
  identifier = "d"
  image = "images/LOGO/images.png"
  alt = "Image Placeholder"

[[params.p3.logos]]
  identifier = "e"
  image = "images/LOGO/download.png"
  alt = "Download Icon"

[[params.p3.logos]]
  identifier = "f"
  image = "images/LOGO/flask.png"
  alt = "Flask Logo"


[params.p4]
  heading = "Explore the Latest Articles"

[[params.p4.content]]
  text = "Stay updated with insightful articles on modern agriculture, technology, and innovation. "

[params.p5]
  heading = "Stay Up to Date"
  action = "#"
  label = "Email address"
  placeholder = "Enter your email"
  button = "Notify me"

[[params.p5.content]]
  text = "Get the latest updates on agriculture, technology, and innovations straight to your inbox!"

[params.social_media]
  [params.social_media.github]
    enabled = true
    url = 'https://github.com/xpushpraj'
  [params.social_media.twitter]
    enabled = true
    url = 'https://twitter.com/Farmfrontiers'
  [params.social_media.instagram]
    enabled = true
    url = 'https://www.instagram.com/xpushpraj'
  [params.social_media.YouTube]
    enabled = true
    url = 'https://www.youtube.com/@Farmfrontiers'
  [params.social_media.LinkedIn]
    enabled = true
    url = 'https://www.youtube.com/@Farmfrontiers'

[menu]
  [[menu.main]]
    identifier = "Agritechs"
    name = "Agritechs"
    url = "/Agritechs/"
    weight = 10

  [[menu.main]]
    identifier = "PAU"
    name = "PAU News"
    url = "/PAU News/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    pre = "dropdown"
    name = "Myself"
    weight = 30

  [[menu.main]]
    identifier = "dropdown"
    pre = "complexdropdown"
    name = "Discover"
    weight = 40

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50

  [[menu.categories]]
    identifier = "Projects"
    name = "Projects"
    url = "/prose/"
    weight = 10

  [[menu.categories]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20

  [[menu.dropdown]]
    identifier = "Career"
    pre = "stars"
    name = "Career"
    post = "Find Future Scope"
    url = "#"
    weight = 10

  [[menu.dropdown]]
    identifier = "comments"
    pre = "comments"
    name = "Comments"
    post = "Check your latest comments"
    url = "#"
    weight = 20

  [[menu.dropdown]]
    identifier = "Other"
    pre = "piechart"
    name = "Other"
    post = "Take a look at Probing"
    url = "#"
    weight = 30

  [[menu.footer]]
    identifier = "Agritechs"
    name = "Agritechs"
    url = "/posts/"
    weight = 10

  [[menu.footer]]
    identifier = "PAU"
    name = "PAU News"
    url = "/PAU News/"
    weight = 20

  [[menu.footer]]
    identifier = "PAU"
    name = "PAU News"
    url = "/PAU News/"
    weight = 30

  [[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

  [[menu.footer]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 50
